rust-embedded/meta-rust-bin

- LICENSE-APACHE
- LICENSE-MIT
- README.md
- classes/cargo.bbclass
- classes/rust-common.bbclass
- conf/layer.conf
- recipes-devtools/rust/cargo-bin.inc
- recipes-devtools/rust/cargo-bin_20160705.bb
- recipes-devtools/rust/rust-bin.inc
- recipes-devtools/rust/rust-bin_1.11.0.bb
This is working well on Dizzy + armv7. I'm planning to run some builds against other versions, but for now I wanted to get this out for review.
@posborne @tmanley
> Initial development of working code

- README.md
- build-new-version.sh
- recipes-devtools/rust/cargo-bin.inc
- recipes-devtools/rust/cargo-bin_20160821.bb
- recipes-devtools/rust/rust-bin_1.12.0.bb
These commits add support for rust 1.12.0 and automate the process of creating new recipes for a specific version of rust by grabbing artifacts and calculating the sha256/md5 checksums.  This should make adding future versions of rust to this layer very easy.
@nastevens
> Rust 1.12.0 support and automation

- classes/cargo.bbclass
The `pkgconfig` crate disables use of pkg-config lookup when
cross-compiling by default.  Within the context of Yocto we
want pkg-config to be used.  We can enable by setting the
`PKG_CONFIG_ALLOW_CROSS` flag.
CC @nastevens
> cargo: enable pkg-config when cross compiling

- build-new-version.sh
- recipes-devtools/rust/cargo-bin_20160821.bb
- recipes-devtools/rust/rust-bin_1.12.1.bb
For now, I revoved powerpc64-unknown-linux-gnu as it was
not published at the time.  Will try to work with upstream
to figure out what is going on there.  I'm guessing nobody
is using it, :shrug:
@nastevens
> rustup: add 1.12.1 support

- build-new-version.sh
- recipes-devtools/rust/cargo-bin_1.11.0.bb
- recipes-devtools/rust/cargo-bin_1.12.0.bb
- recipes-devtools/rust/cargo-bin_1.12.1.bb
- recipes-devtools/rust/cargo-bin_1.14.0.bb
- recipes-devtools/rust/cargo-bin_1.15.0.bb
- recipes-devtools/rust/rust-bin_1.15.0.bb
Add rust 1.15.0 and update cargo versioning strategy to match rust release it was introduced with.
> Rust 1.15.0

- build-new-version.sh
- recipes-devtools/rust/cargo-bin.inc
- recipes-devtools/rust/cargo-bin_1.11.0.bb
- recipes-devtools/rust/cargo-bin_1.12.0.bb
- recipes-devtools/rust/cargo-bin_1.12.1.bb
- recipes-devtools/rust/cargo-bin_1.14.0.bb
- recipes-devtools/rust/cargo-bin_1.15.0.bb
- recipes-devtools/rust/cargo-bin_1.15.1.bb
- recipes-devtools/rust/cargo-bin_1.16.0.bb
- recipes-devtools/rust/rust-bin_1.11.0.bb
- recipes-devtools/rust/rust-bin_1.12.0.bb
- recipes-devtools/rust/rust-bin_1.12.1.bb
- recipes-devtools/rust/rust-bin_1.14.0.bb
- recipes-devtools/rust/rust-bin_1.15.0.bb
- recipes-devtools/rust/rust-bin_1.15.1.bb
- recipes-devtools/rust/rust-bin_1.16.0.bb
Since at least version 1.15.1 and possibly before the download
URL for cargo was not being constructed correctly. Now the URL
is grabbed directly from the `channel-rust-<version>.toml`. All
of the existing recipes were regenerated with the updated
`build-new-version.sh` script.
> Fix cargo download URLs and add recipes for rust 1.16.0

- build-new-version.sh
- recipes-devtools/rust/cargo-bin.inc
- recipes-devtools/rust/cargo-bin_1.21.0.bb
- recipes-devtools/rust/rust-bin_1.21.0.bb
There were a few changes upstream that required changes to core
recipes.  I believe this doesn't break the older versions although
you will no longer be able to use the same script to regenerate
older rust versions (which should be fine).
CC @tpmanley
> rustup: add support for rustc 1.21.0

- classes/cargo.bbclass
Enable debug symbols in release mode. Note that this doesn't add any additional overhead since the debug symbols will be stripped to a `-dbg` package either way.
> Enable debug symbols when building --release

- build-new-version.sh
- classes/cargo.bbclass
- recipes-devtools/rust/cargo-bin-cross.inc
- recipes-devtools/rust/cargo-bin-cross_1.11.0.bb
- recipes-devtools/rust/cargo-bin-cross_1.12.0.bb
- recipes-devtools/rust/cargo-bin-cross_1.12.1.bb
- recipes-devtools/rust/cargo-bin-cross_1.14.0.bb
- recipes-devtools/rust/cargo-bin-cross_1.15.0.bb
- recipes-devtools/rust/cargo-bin-cross_1.15.1.bb
- recipes-devtools/rust/cargo-bin-cross_1.16.0.bb
- recipes-devtools/rust/cargo-bin-cross_1.21.0.bb
- recipes-devtools/rust/cargo-bin-cross_1.22.1.bb
- recipes-devtools/rust/cargo-bin-cross_1.23.0.bb
- recipes-devtools/rust/rust-bin-cross.inc
- recipes-devtools/rust/rust-bin-cross_1.11.0.bb
- recipes-devtools/rust/rust-bin-cross_1.12.0.bb
- recipes-devtools/rust/rust-bin-cross_1.12.1.bb
- recipes-devtools/rust/rust-bin-cross_1.14.0.bb
- recipes-devtools/rust/rust-bin-cross_1.15.0.bb
- recipes-devtools/rust/rust-bin-cross_1.15.1.bb
- recipes-devtools/rust/rust-bin-cross_1.16.0.bb
- recipes-devtools/rust/rust-bin-cross_1.21.0.bb
- recipes-devtools/rust/rust-bin-cross_1.22.1.bb
- recipes-devtools/rust/rust-bin-cross_1.23.0.bb
Sometimes you review old code and wonder what exactly you were thinking at the time... In this case, I thought that twice.
First, for my understanding of how to build cross-compiled packages was wrong. I was using nativesdk and native class extensions, when really I needed to `inherit cross` and then change the `PN` of the recipe to match the target architecture. I learned the correct way to deal with this from a close review of the [oe-meta-go](https://github.com/mem/oe-meta-go) recipes.
Second, I was keying off of the `-dbg` package types to determine whether or not to build `--release`. That is also straight-up wrong, since almost all normal builds will not have `-dbg`. I've fixed this by introducing a `CARGO_BUILD_TYPE` variable that can be set if the default of `--release` is not the …
> Fix yocto misunderstandings

- classes/rust-common.bbclass
Yocto adds a vardep to `rust_target` on the string `rust_target[vardeps]` which then causes taskhash mismatches because the string contents of that variable changes each time the code is built. We don't actually care about the `rust_target[vardeps]` string, we care about the vardeps that string specifies (`*_ARCH`/`*_OS`). This PR adds a vardepsexclude for `rust_target[vardeps]`.
> Eliminate "rust_target[vardeps]" taskhash mismatches

- classes/rust-common.bbclass
- recipes-devtools/rust/cargo-bin-cross.inc
- recipes-devtools/rust/rust-bin-cross.inc
Fix for an issue that @krupatil was seeing - the problem was that for the CPU being used (an i.MX6ULL), the `armv7` TUNE_FEATURE was `armv7ve`, not `armv7a`. That led to the `arm` target being installed instead of `armv7`, and the user package not being able to find the armv7 target.
> Fix detection of armv7 targets

- classes/cargo.bbclass
This fix errors like `NameError: name 'base_conditional' is not defined` on latest poky master
> use oe.utils.conditional instead of deprecated base_conditional

- recipes-devtools/rust/cargo-bin-cross_1.25.0.bb
- recipes-devtools/rust/rust-bin-cross_1.25.0.bb
I just ran the updating script:
% ./build-new-version.sh 1.25.0
---
BTW, I've noticed that this layer does not install rustc and cargo into ${SYSROOTS}/x86_64-linux on Yocto 2.1(jethro).
Is this behavior intended?
I guess this behavior prevents mixing binaries for different architectures.
> Generated rust stable 1.25.0 recipes.

- recipes-devtools/rust/cargo-bin-cross_1.27.2.bb
- recipes-devtools/rust/rust-bin-cross_1.27.2.bb
Just ran `build-new-version.sh`.
> Generated rust stable 1.27.2 recipes.

- build-new-version.sh
- recipes-devtools/rust/cargo-bin-cross_1.30.0.bb
- recipes-devtools/rust/cargo-bin-cross_1.30.1.bb
- recipes-devtools/rust/rust-bin-cross_1.30.0.bb
- recipes-devtools/rust/rust-bin-cross_1.30.1.bb
Be gentle, still lerning how to do PR.
Add 1.30.0 support
> Add Rust 1.30.0

- conf/layer.conf
LAYERSERIES_COMPAT: Lists the Yocto Project releases for which the current version is compatible. If this variable is not set, bitbake prints a warnings like this:
```
WARNING: Layer rust-bin-layer should set LAYERSERIES_COMPAT_rust-bin-layer in its conf/layer.conf file to list the core layer names it is compatible with.
```
See: https://www.yoctoproject.org/docs/current/mega-manual/mega-manual.html#var-LAYERSERIES_COMPAT
> Fix warnings about LAYERSERIES_COMPAT

- classes/cargo.bbclass
Creates an overridable variable `CARGO_MANIFEST_PATH` for cases where
the `Cargo.toml` may not be at `${S}` root, such as with multi-crate or
workspace-based repositories.
> Expose Cargo manifest path variable

- recipes-devtools/rust/cargo-bin-cross_1.34.2.bb
- recipes-devtools/rust/cargo-bin-cross_1.35.0.bb
- recipes-devtools/rust/rust-bin-cross_1.34.2.bb
- recipes-devtools/rust/rust-bin-cross_1.35.0.bb
Adds the latest stable Rust and the latest patch version of 1.34.
> Rust 1.35.0 & 1.34.2

- build-new-version.sh
- recipes-devtools/rust/cargo-bin-cross_1.35.0.bb
The Apache license URL changed to https in cargo 0.36.0. This breaks the Rust 1.35.0 recipe.
This PR fixes the 1.35.0 recipe and adds a cargo license validation step.
2d66d2f adds shellharden changes and other modifications for improved correctness. This commit is optional.
> Fix license for Rust 1.35.0 & add a check to avoid surprises in the future

- classes/cargo.bbclass
Time for another round of guess the obscure shell issue!
The existing implementation of the wrapper scripts (cc-wrapper, linker-wrapper, et. al.) was passing any additional arguments to the compiler by using just `$@`. This is different than `"$@"` - while it seems like `"$@"` would put all arguments into a single, quoted expansion, it actually has a special meaning that passes arguments as-is to the underlying program being called.
This was discovered when an additional argument to the cc-wrapper script, which was properly escaped initially, caused a failure to build using meta-rust-bin because escaped quotes were being evaluated twice. It's easiest to see in an example.
The Rust crate being compiled calls out to the C compiler, i.e. our script, as follows:
cc-wrapper.sh "MY_ARG=\"value …
> fix: double-evaluation of escaped variables in wrappers

- classes/cargo.bbclass
The check, for this specific layer case, must be done using the Rust
specific targets as the vendor of toolchain is ignored blindly.
> cargo: Fix cross compiling check to use RUST_BUILD and RUST_TARGET

- classes/rust-common.bbclass
This change essentially address an issue caused by upstream changes in the
poky repo around arch and cpu specific tunes.  Changes shown in the referenced
commit are causing target rust libraries to not being installed correctly in the
sysroot-native path resulting in compilation failures as shown below
For reference - this is the commit in the poky repo
https://git.yoctoproject.org/cgit.cgi/poky/commit/meta/conf/machine/include?h=warrior&id=156a2d98600299822695d173381a9eac49e30908
(In this example an armv7 cpu is being used, however, the installed lib dir is incorrectly installed)
recipe-sysroot-native/usr/lib/rustlib/
├── arm-unknown-linux-gnueabihf
│   └── lib
├── etc
└── x86_64-unknown-linux-gnu
├── bin
├── codegen-backends
└── lib
which causes failures such as:
error[E0463]: can't …
> arm arch tune varibles have been moved to MACHINEOVERRIDES in Warrior

- classes/cargo.bbclass
Could it be that wrappers are also needed for the `CXX` compiler? Without this modification I'm unable the compile the `zmq` crate (with vendored ZeroMQ source). See below:
---
```
process didn't exit successfully: `/build/tmp/raspberrypi/raspberrypi-glibc/work/arm1176jzfshf-vfp-oe-linux-gnueabi/chirpstack-concentratord-sx1301/3.0.0-test.5-r10/target/release/build/zmq-sys-21a1e6ece6cec0e5/build-script-main` (exit code: 101)
| --- stdout
| cargo:rerun-if-changed=build/main.rs
| cargo:rerun-if-env-changed=PROFILE
| running: "cmake" "/build/tmp/raspberrypi/raspberrypi-glibc/work/arm1176jzfshf-vfp-oe-linux-gnueabi/chirpstack-concentratord-sx1301/3.0.0-test.5-r10/cargo_home/registry/src/github.com-1ecc6299db9ec823/zeromq-src-0.1.8+4.3.2/vendor" "-DCMAKE_INSTALL_LIBDIR=lib" …
```
> Fix CXX compiler errors.

- classes/cargo.bbclass
this change allows `RUSTFLAGS` to be passed to the cargo build command, i.e. you can add this to your recipe append file : `EXTRA_RUSTFLAGS="-C target-cpu=cortex-a75"` or enable debug symbol in a release build `EXTRA_RUSTFLAGS="-g"`
> Add RUSTFLAGS support

- build-new-version.sh
At the moment, the `build-new-version.sh` happily continues even if a download failed (e.g. due to a 404). This fixes that.
> Stop on download error

- classes/cargo.bbclass
When we have same architecture for the host and target, we need to
properly handle the native and target case as Rust cannot differentiate
both.
Fixes: #70.
> class/cargo: Handle case when host and target has same arch

- recipes-devtools/rust/cargo-bin-cross_1.47.0.bb
- recipes-devtools/rust/cargo-bin-cross_1.48.0.bb
- recipes-devtools/rust/cargo-bin-cross_1.49.0.bb
- recipes-devtools/rust/rust-bin-cross_1.47.0.bb
- recipes-devtools/rust/rust-bin-cross_1.48.0.bb
- recipes-devtools/rust/rust-bin-cross_1.49.0.bb
This commit adds the 
* [1.47.0](https://blog.rust-lang.org/2020/10/08/Rust-1.47.html)
* [1.48.0](https://blog.rust-lang.org/2020/11/19/Rust-1.48.html)
* [1.49.0](https://blog.rust-lang.org/2020/12/31/Rust-1.49.0.html)
release of the rust language to this repo
> update to latest compiler

- classes/cargo.bbclass
To amend this issue: https://github.com/rust-embedded/meta-rust-bin/issues/90
> specify install dir via CARGO_INSTALL_DIR

- recipes-devtools/rust/cargo-bin-cross_1.53.0.bb
- recipes-devtools/rust/cargo-bin-cross_1.54.0.bb
- recipes-devtools/rust/rust-bin-cross_1.53.0.bb
- recipes-devtools/rust/rust-bin-cross_1.54.0.bb
Generated via `build-new-version.sh`.
> Rust 1.53.0 and 1.54.0

- classes/cargo.bbclass
[#119](https://github.com/rust-embedded/meta-rust-bin/pull/119) added the feature to install examples and libraries by default if they exist. An unintended consequence of that though was breaking existing builds when a .rlib file was installed but then not included in the FILES directive.
To keep parity with meta-rust we'll start packaging .rlib files in the -dbg package.
> Include .rlib files in -dev package

- recipes-devtools/rust/cargo-bin-cross_1.62.1.bb
- recipes-devtools/rust/cargo-bin-cross_1.63.0.bb
- recipes-devtools/rust/rust-bin-cross_1.62.1.bb
- recipes-devtools/rust/rust-bin-cross_1.63.0.bb
Contents created by running `build-new-version.sh`.
> Add Rust 1.62.1, 1.63.0

- README.md
- conf/layer.conf
- recipes-devtools/rust/cargo-bin-cross.inc
- recipes-devtools/rust/rust-bin-cross.inc
Updating the meta-rust-bin to support the kirkstone compatibility layer. Updated the README.md example recipe.
[Yocto Kirkstone Migration SYSROOT_DIRS_BLACKLIST to SYSROOT_DIRS_IGNORE](https://docs.yoctoproject.org/dev/migration-guides/migration-4.0.html)
There are changes included in this PR suggested by https://github.com/rust-embedded/meta-rust-bin/pull/111.
> Add kirkstone to compatibility layer

- README.md
- build-new-version.sh
- recipes-devtools/rust/cargo-bin-cross.inc
- recipes-devtools/rust/rust-bin-cross.inc
1. `build-new-version.sh`: added support to download specified nightly version
2. fix `cargo-bin-cross.inc` and `rust-bin-cross.inc` to support nightly version
3. added nightly 2019-07-08 version recipe ( [optee](https://github.com/apache/incubator-teaclave-trustzone-sdk) requires specified nightly version )
Question: How can I specify a toolchain only to certain recipe? PREFERRED_VERSION only support selection of toolchain globally.
> Added specified nightly toolchain support

- README.md
Rust support was added to open embedded-core in the 3.4 honister release. This change just adds a note to the README file.
> Add a note about BBMASK to avoid conflicts with poky rust recipe

- README.md
- add note on task network access for kirkstone and above
- rebuild the toc 
Related to: https://github.com/rust-embedded/meta-rust-bin/issues/130
> doc: network access for do_compile with kirkstone and above

- README.md
- recipes-devtools/rust/cargo-bin-cross_1.66.0.bb
- recipes-devtools/rust/cargo-bin-cross_1.66.1.bb
- recipes-devtools/rust/rust-bin-cross_1.66.0.bb
- recipes-devtools/rust/rust-bin-cross_1.66.1.bb
Autogenerated by running `build-new-version.sh 1.66.0`.  Updated the README too.
> Add Rust 1.66.0 & 1.66.1

- README.md
- recipes-devtools/rust/cargo-bin-cross_1.67.0.bb
- recipes-devtools/rust/cargo-bin-cross_1.67.1.bb
- recipes-devtools/rust/cargo-bin-cross_1.68.0.bb
- recipes-devtools/rust/rust-bin-cross_1.67.0.bb
- recipes-devtools/rust/rust-bin-cross_1.67.1.bb
- recipes-devtools/rust/rust-bin-cross_1.68.0.bb
Autogenerated by running `build-new-version.sh`. Updated the README too.
> Add Rust 1.67.0, 167.1, 1.68.0

- README.md
- recipes-devtools/rust/cargo-bin-cross_1.69.0.bb
- recipes-devtools/rust/cargo-bin-cross_1.70.0.bb
- recipes-devtools/rust/rust-bin-cross_1.69.0.bb
- recipes-devtools/rust/rust-bin-cross_1.70.0.bb
Adds `1.69.0` and `1.70.0`, generated by `build-new-version.sh`.
> Add Rust 1.69.0 and 1.70.0

- classes/cargo.bbclass
Cargo can use this environment variable to authenticate private ssh repo dependencies
> Export SSH_AUTH_SOCK to cargo build

- README.md
- recipes-devtools/rust/cargo-bin-cross_1.71.1.bb
- recipes-devtools/rust/cargo-bin-cross_1.72.0.bb
- recipes-devtools/rust/cargo-bin-cross_1.72.1.bb
- recipes-devtools/rust/cargo-bin-cross_1.73.0.bb
- recipes-devtools/rust/rust-bin-cross_1.71.1.bb
- recipes-devtools/rust/rust-bin-cross_1.72.0.bb
- recipes-devtools/rust/rust-bin-cross_1.72.1.bb
- recipes-devtools/rust/rust-bin-cross_1.73.0.bb
Add recipes for Rust versions from v1.71.1 to v1.73.0.
_Note_
v1.71.1 does include `mips-unknown-linux-gnu` and `mipsel-unknown-linux-gnu` (See #145)
> Rust v1.73.0

- classes/cargo_bin.bbclass
In #82 we fixed the build when the target arch is the same as the build arch. A side effect of the fix is that the rust build-scripts (which are intended to run on the build host) are now built with the target compiler and cflags.
This is fine in most cases but it breaks when the host system is older than the system we are building. For example, we might build for a newer glibc that will be available on the target but when we run the build script on the host, this version does not exist which leads to the error described in #83.
Another version of the same problem is that we may try to use some build flags that are available on the compiler for the target (`aarch64-poky-linux-gcc`) but not on the host compiler (`gcc`) because the host compiler is an older version of gcc than the one we …
> fix: build when target_arch==build_arch

- classes/cargo_bin.bbclass
Solves #151
I'm not sure if 'BUILD' was set on purpose or not, but on a cross-compilation scenario it's surely not desired.
> fix(cargo-linker): variable case and value

- README.md
We have automation around creating the new recipe bump.  Having documentation around the current latest version tends to get missed, so this change drops it in favor of just informing users of where to look to confirm which versions are supported in tree.
See discussion in https://github.com/rust-embedded/meta-rust-bin/pull/164#issuecomment-1936795903, CC @cordahi
> Remove specific rust version from readme

- classes/cargo_bin.bbclass
From https://doc.rust-lang.org/cargo/guide/build-cache.html
> For historical reasons, the dev and test profiles are stored in the
> debug directory, and the release and bench profiles are stored in the
> release directory. User-defined profiles are stored in a directory with
> the same name as the profile.
Fixes #167, CC @DavidAntliff
> correctly handle dev, bench, test profiles

- classes/rust_bin-common.bbclass
When checking that we're targeting a valid architecture and OS there is an unintentional case-sensitive test. So the OS 'Linux' is not accepted, it'd have to be 'linux'.
I fixed this up by making the OS, arch, and tune parameter checks case-insensitive.
See https://github.com/rust-embedded/meta-rust-bin/issues/171
> Ignore string case when checking ARCH, OS, and TUNE variables

- classes/cargo_bin.bbclass
Hi,
Thanks for this project :)
I encountered an issue when trying to cross compile [vector](https://github.com/vectordotdev/vector) using Yocto Scarthgap for an aarch64 platform (e.g. Raspberry Pi 4) : 
```
| error: failed to run custom build command for `krb5-src v0.3.2+1.19.2`
| 
| Caused by:
|   process didn't exit successfully: `/workspaces/omnios_rust_bin/build/tmp/work/cortexa72-poky-linux/vector/0.44.0/target/release/build/krb5-src-7d691da815ca739d/build-script-build` (exit status: 101)
|   --- stdout
|   checking for aarch64-unknown-linux-gnu-gcc... /workspaces/omnios_rust_bin/build/tmp/work/cortexa72-poky-linux/vector/0.44.0/wrappers/cc-native-wrapper.sh
|   checking whether the C compiler works... no
| 
|   --- stderr
|   configure: error: in …
```
> Fix CC pointing to wrong compiler
