rust-embedded/meta-rust-bin

recipes-devtools/rust/cargo-bin_298a0127f703d4c2500bb06d309488b92ef84ae1.bb
recipes-devtools/rust/rust-bin_1.14.0.bb

rustup: add support for rust 1.14.0

---

classes/cargo.bbclass

This add three new wrappers scripts :
- native CC for compiling C code that ought to be executed on the
build machine, for example in a build.rs script
- LD for linking for the target using the LDFLAGS provided by Yocto
- native LD for linking code for the build machine
These wrapper scripts are set accordingly in the cargo config and the
appropriate scoped environment variables. Note that the LDFLAGS
variable is emptied before calling cargo as is contains flags for
linking for the target but may be misinterpreted by cargo as being
flags for the build machine (flags are passed in the wrappers so this
should not be a problem)

Better wrappers for CC and LD

---

classes/rust-common.bbclass
recipes-devtools/rust/cargo-bin-cross.inc
recipes-devtools/rust/rust-bin-cross.inc

Two semi-related commits for fixing issues around caching and cache generation. See commit messages for details.

Fix caching issues

---

recipes-devtools/rust/cargo-bin-cross_1.24.0.bb
recipes-devtools/rust/rust-bin-cross_1.24.0.bb

Not much to see here, just ran the script =).

Generated rust stable 1.24.0 recipes.

---

build-new-version.sh
recipes-devtools/rust/cargo-bin-cross_1.26.0.bb
recipes-devtools/rust/rust-bin-cross_1.26.0.bb

Signed-off-by: Paul Osborne <osbpau@gmail.com>

Add rust 1.26

---

recipes-devtools/rust/cargo-bin-cross_1.31.0.bb
recipes-devtools/rust/rust-bin-cross_1.31.0.bb

Only run script, no actual test.

Add 1.31.0

---

conf/layer.conf

otherwise trying to build with rocko will fail

add rocko to the layer compat

---

classes/cargo.bbclass
conf/layer.conf
recipes-devtools/rust/cargo-bin-cross_1.36.0.bb
recipes-devtools/rust/rust-bin-cross_1.36.0.bb

Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>

conf/layer.conf: Add thud and warrior to compatible list

---

conf/layer.conf

Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>

conf/layer.conf: add dunfell compatibility

---

README.md
recipes-devtools/rust/cargo-bin-cross_1.44.0.bb
recipes-devtools/rust/rust-bin-cross_1.44.0.bb

Add Rust 1.44.0 release

---

recipes-devtools/rust/cargo-bin-cross_1.45.0.bb
recipes-devtools/rust/rust-bin-cross_1.45.0.bb

rust: Add 1.45.0

---

recipes-devtools/rust/cargo-bin-cross_1.45.2.bb
recipes-devtools/rust/rust-bin-cross_1.45.2.bb

rust: add 1.45.2 recipes

---

conf/layer.conf

conf/layer.conf: Add gatesgarth as compatible

---

conf/layer.conf

Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>

conf/layer.conf: Add hardknott to LAYERSERIES_COMPAT

---

classes/cargo.bbclass

copied from https://github.com/meta-rust/meta-rust/blob/master/classes/cargo.bbclass#L57

Install lib and bin each in their respective destination folder

---

recipes-devtools/rust/cargo-bin-cross_1.64.0.bb
recipes-devtools/rust/rust-bin-cross_1.64.0.bb

Autogenerated by running `build-new-version.sh 1.64.0`

Add Rust 1.64.0

---

README.md
recipes-devtools/rust/cargo-bin-cross_1.65.0.bb
recipes-devtools/rust/rust-bin-cross_1.65.0.bb

Autogenerated by running `build-new-version.sh 1.65.0`

Add Rust 1.65.0

---

build-new-version.sh
classes/rust_bin-common.bbclass
recipes-devtools/rust/rust-bin-cross_1.73.0.bb

- Add riscv64 target
- Regenerated latest 1.73.0 recipe to include riscv64

riscv64 target

---

README.md
recipes-devtools/rust/cargo-bin-cross_1.74.0.bb
recipes-devtools/rust/rust-bin-cross_1.74.0.bb

Add recipes for Rust version 1.74.0.

Rust v1.74.0

---

conf/layer.conf

enable the layer for mickledore and nanbield

Add support for mickledore and nanbield

---

classes/cargo_bin.bbclass
recipes-devtools/rust/cargo-bin-cross.inc
recipes-devtools/rust/rust-bin-cross.inc

I was having a nightmare trying to squash my existing branch and ended up making new one, so here it is as a single commit.

Allow native builds

---

conf/layer.conf

Hi all,
this PR adds support for scarthgap. I tested it without any issues.
greets,
mr-nice

conf/layer.conf: add support for scarthgap

---

build-new-version.sh
recipes-devtools/rust/rust-bin-cross_1.80.0.bb

Add thumbv7neon target to the recipe. Also ran build-new-version for 1.80

Add thumbv7neon target
